#!/usr/bin/env python3
"""Generate Russian narration and real word timings for a Remotion mini-story.

Free Edge neural voice. No API key or paid subscription. Service availability is
external, so unavailable/invalid narration MUST fail the video build rather
than silently producing a speech-free published MP4.
"""
from __future__ import annotations
import asyncio
import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path

import edge_tts

ROOT = Path(__file__).resolve().parents[1]
PHASES = ("intro", "danger", "choicesIntro", "decision", "jumpOutcome", "dragonOutcome", "ropeOutcome", "outro")
VOICE = os.environ.get("HERO_VOICE", "ru-RU-DmitryNeural")
RATE = os.environ.get("HERO_VOICE_RATE", "+10%")
OUT = ROOT / "assets" / "voice"
MANIFEST = ROOT / "src" / "generated" / "voice-timings.json"
SEVEN_DIGIT_SECOND = 10_000_000


def probe_duration(filename: Path) -> float:
    result = subprocess.run([
        "ffprobe", "-v", "error", "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1", str(filename)
    ], check=True, capture_output=True, text=True)
    return float(result.stdout.strip())


async def synthesize(text: str, filename: Path) -> list[dict]:
    filename.parent.mkdir(parents=True, exist_ok=True)
    words: list[dict] = []
    total = 0
    talk = edge_tts.Communicate(text=text, voice=VOICE, rate=RATE, boundary="WordBoundary")
    with filename.open("wb") as out:
        async for item in talk.stream():
            if item["type"] == "audio":
                audio = item["data"]
                total += len(audio)
                out.write(audio)
            elif item["type"] == "WordBoundary":
                words.append({
                    "spoken": item["text"],
                    "start": item["offset"] / SEVEN_DIGIT_SECOND,
                    "end": (item["offset"] + item["duration"]) / SEVEN_DIGIT_SECOND,
                })
    if total < 2500 or len(words) < 2:
        raise RuntimeError(f"No valid spoken audio / timestamps for: {text!r} (audio bytes={total}, words={len(words)})")
    original_tokens = re.findall(r"\S+", text)
    # Word boundaries are generated by the SAME TTS request that rendered audio.
    # Verify token count so printed captions do not silently drift from voice.
    if len(original_tokens) != len(words):
        raise RuntimeError(
            f"Voice boundary mismatch: {len(original_tokens)} written words, "
            f"{len(words)} spoken boundaries, narration={text!r}, "
            f"boundaries={[w['spoken'] for w in words]}"
        )
    for token, word in zip(original_tokens, words):
        word["text"] = token
        word.pop("spoken")
    return words


def retime_if_needed(path: Path, words: list[dict], allotted: float) -> float:
    duration = probe_duration(path)
    maximum = allotted - 0.10
    if duration <= maximum:
        return duration
    speed = max(1.0, duration / maximum * 1.02)
    if speed > 1.4:
        raise RuntimeError(f"Voice too long ({duration:.2f}s vs {allotted:.2f}s); shorten script instead of speaking unnaturally fast")
    temp = path.with_suffix(".tmp.mp3")
    try:
        subprocess.run([
            "ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", str(path),
            "-filter:a", f"atempo={speed:.6f}",
            "-codec:a", "libmp3lame", "-q:a", "3", str(temp)
        ], check=True)
        temp.replace(path)
    finally:
        temp.unlink(missing_ok=True)
    for word in words:
        word["start"] /= speed
        word["end"] /= speed
    after = probe_duration(path)
    if after > allotted + 0.015:
        raise RuntimeError(f"Retimed voice still overruns {allotted}s: {after}s")
    return after


def validate_audibility(filename: Path) -> None:
    # Decode to PCM for basic sanity: it must be a decodable audio stream with
    # positive duration and nonzero sound level, not an empty or fake MP3.
    proc = subprocess.run([
        "ffmpeg", "-hide_banner", "-i", str(filename),
        "-af", "volumedetect", "-f", "null", "-"
    ], stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, text=True)
    match = re.search(r"mean_volume:\s*(-?\d+(?:\.\d+)?) dB", proc.stderr)
    if proc.returncode != 0 or match is None or float(match.group(1)) < -45:
        raise RuntimeError(f"Narration file is silent or invalid: {filename}")


async def main() -> None:
    episode = json.loads((ROOT / "episodes" / "episode-001.json").read_text(encoding="utf-8"))
    if not re.fullmatch(r"episode-\d{3}", episode["id"]):
        raise RuntimeError("Invalid episode ID")
    signature = hashlib.sha256(json.dumps({"episode": episode, "voice": VOICE, "rate": RATE}, ensure_ascii=False, sort_keys=True).encode("utf-8")).hexdigest()
    if MANIFEST.exists():
        try:
            previous = json.loads(MANIFEST.read_text(encoding="utf-8"))
            if previous.get("source_hash") == signature and all(
                (OUT / f"{episode['id']}-{phase}.mp3").stat().st_size > 2500 for phase in PHASES
            ):
                print("VOICE CACHE HIT: eight real clips match exact episode text and voice settings", flush=True)
                return
        except (OSError, KeyError, ValueError):
            pass
    manifest = {"id": episode["id"], "voice": VOICE, "source_hash": signature, "phases": {}}
    OUT.mkdir(parents=True, exist_ok=True)
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)

    for phase in PHASES:
        obj = episode[phase]
        path = OUT / f"{episode['id']}-{phase}.mp3"
        narration = obj["narration"]
        last_error = None
        for attempt in range(12):
            try:
                words = await synthesize(narration, path)
                seconds = retime_if_needed(path, words, float(obj["seconds"]))
                validate_audibility(path)
                end = max(w["end"] for w in words)
                if end > float(obj["seconds"]) + .03:
                    raise RuntimeError(f"{phase} final spoken word exceeds phase duration")
                manifest["phases"][phase] = {
                    "file": f"voice/{path.name}",
                    "duration": round(seconds, 3),
                    "words": [{
                        "text": w["text"],
                        "start": round(w["start"], 3),
                        "end": round(w["end"], 3),
                    } for w in words],
                }
                print(f"VOICE OK {phase:<12} {seconds:.2f}s / {obj['seconds']}s, {len(words)} words, {path.stat().st_size} bytes", flush=True)
                break
            except Exception as exc:
                last_error = exc
                path.unlink(missing_ok=True)
                print(f"VOICE RETRY {phase} attempt {attempt+1}/12: {exc}", flush=True)
                await asyncio.sleep(min(18, 2.5 + attempt * 1.8))
        else:
            raise RuntimeError(f"Voice generation failed for {phase}: {last_error}")

    if set(manifest["phases"]) != set(PHASES):
        raise RuntimeError("Missing narration phases")
    MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"8 valid spoken tracks and timestamped captions -> {MANIFEST.relative_to(ROOT)}", flush=True)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except Exception as exc:
        print(f"ERROR (narration generation, NOT a silent fallback): {exc}", file=sys.stderr)
        sys.exit(1)
